name: MS Teams Ingegration POC
on:
  push:
    branches:  
      - main
      - feature/**
  pull_request:
    branches: [ main ]
jobs:
  MSTeamsAlertGenerator:
    runs-on: ubuntu-latest
    name: MSTeamsAlertGenerator
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: GitHub Pipeline Status Alert
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          webhook-uri: ${{ secrets.MSTEAM_WEBHOOK }}
          card-layout-start: complete
          card-layout-exit: complete
          show-on-start: true
          show-on-exit: true
          environment: development
          custom-facts: |
            - name: Initiated by
              value: ${{ github.actor }}
            - name: Workflow name
              value: ${{ github.workflow }}
          custom-actions: |
            - text: View Job Execution Status
              url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: "install nodejs 12.13.0"
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - name: "run npm build tasks"
        run: npm install
      - name: "run npm test cases"
        run: npm run test
      - name: "run sonar analysis"
        run: |
           npm run testWithCoverage
           branch=$(echo $GITHUB_REF | awk -F/ '{print $NF}')
           curl -v -X POST https://${{ secrets.SONAR_TOKEN }}@sonarcloud.io/api/projects/create -d "name=nodejs-semver-${branch}&project=nodejs-semver-watsap&organization=${{ secrets.SONAR_ORG }}"
      - name: "publish sonar dashboard"
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          args: >
           -Dsonar.projectKey=nodejs-semver-watsap
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Sonar Validation
        run: |
          bash SonarBuildBreaker.sh --sonar-url=https://sonarcloud.io --sonar-token=${{ secrets.SONAR_TOKEN }} --project-key=nodejs-semver-watsap --branch=feature/test3
      - name: "May not run"
        run: echo "Extra step, only runs if Sonar Validation passes."
